In [9]:
import pandas as pd
import numpy as np

# Pandas DataFrame

## Scalar Series
Series is a 1-Dimentional labeled array

In [25]:
# create scalar series
scalar = pd.Series(5)
print(scalar)
print(scalar[0])
print(scalar.ndim)
print(scalar.dtype)
print(scalar.shape)
print(scalar.index)
print(list(scalar.keys()))
print(list(scalar.values))

0    5
dtype: int64
5
1
int64
(1,)
RangeIndex(start=0, stop=1, step=1)
[0]
[np.int64(5)]

In [30]:
# scalar arithmetic operations
scalar2 = pd.Series(8)
print(scalar+10)
print(scalar-20)
print(scalar*7)
print(scalar%3)
print(scalar/2)
print(scalar//4)
print(scalar**6)
print(scalar^7)
print(scalar+scalar2)
print(scalar-scalar2)
print(scalar*scalar2)
print(scalar%scalar2)
print(scalar/scalar2)
print(scalar//scalar2)
print(scalar**scalar2)
print(scalar^scalar2)

0    15
dtype: int64
0   -15
dtype: int64
0    35
dtype: int64
0    2
dtype: int64
0    2.5
dtype: float64
0    1
dtype: int64
0    15625
dtype: int64
0    2
dtype: int64
0    13
dtype: int64
0   -3
dtype: int64
0    40
dtype: int64
0    5
dtype: int64
0    0.625
dtype: float64
0    0
dtype: int64
0    390625
dtype: int64
0    13
dtype: int64

In [32]:
# comparision operations
scalar2 = pd.Series(8)
print(scalar==10)
print(scalar!=20)
print(scalar>7)
print(scalar<3)
print(scalar>=2)
print(scalar<=4)
print(scalar==scalar2)
print(scalar!=scalar2)
print(scalar>scalar2)
print(scalar<scalar2)
print(scalar>=scalar2)
print(scalar<=scalar2)

0    False
dtype: bool
0    True
dtype: bool
0    False
dtype: bool
0    False
dtype: bool
0    True
dtype: bool
0    False
dtype: bool
0    False
dtype: bool
0    True
dtype: bool
0    False
dtype: bool
0    True
dtype: bool
0    False
dtype: bool
0    True
dtype: bool

In [37]:
# set name
scalar = pd.Series(10, name='Num1')
scalar2 = pd.Series(8, name='Num2')
print(scalar)
print(scalar2)

0    10
Name: Num1, dtype: int64
0    8
Name: Num2, dtype: int64

In [39]:
# set index
scalar = pd.Series(10,index=['A'])
scalar2 = pd.Series(8,index=['B'])
print(scalar)
print(scalar2)

A    10
dtype: int64
B    8
dtype: int64

In [44]:
# concat scalar series
A = pd.Series(6, index=['A'], name='Num1')
B = pd.Series(8, index=['B'], name='Num2')
scalar = pd.concat((A, B))
print(scalar)
print(scalar['A'])
print(scalar['B'])
print(scalar.ndim)
print(scalar.shape)
print(scalar.dtype)

A    6
B    8
dtype: int64
6
8
1
(2,)
int64

## list and ndarray

In [63]:
A = pd.Series([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
print(A)
B = pd.Series(np.arange(101, 111))
print(B)
print(B[:])
print(B[:7])
print(B[::-1])
B[5:9]=[206,207,208,209]
print(B)

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
dtype: int64
0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
dtype: int64
0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
dtype: int64
0    101
1    102
2    103
3    104
4    105
5    106
6    107
dtype: int64
9    110
8    109
7    108
6    107
5    106
4    105
3    104
2    103
1    102
0    101
dtype: int64
0    101
1    102
2    103
3    104
4    105
5    206
6    207
7    208
8    209
9    110
dtype: int64

In [66]:
## dict series
series = pd.Series({'Name': 'Dhanasekaran', 'Age': 32, 'Gender': 'Male'})
print(series)
print(series['Name'])
print(series['Age'])
print(series[['Name', 'Gender']])

Name      Dhanasekaran
Age                 32
Gender            Male
dtype: object
Dhanasekaran
32
Name      Dhanasekaran
Gender            Male
dtype: object

## DataFrame

In [74]:
# create dataframe
df = pd.DataFrame([np.arange(100, 111)])
print(df)
print(df.ndim)
print(df.shape)

    0    1    2    3    4    5    6    7    8    9    10
0  100  101  102  103  104  105  106  107  108  109  110
2
(1, 11)

In [75]:
df = pd.DataFrame(np.arange(100, 111))
print(df)
print(df.ndim)
print(df.shape)

      0
0   100
1   101
2   102
3   103
4   104
5   105
6   106
7   107
8   108
9   109
10  110
2
(11, 1)

In [8]:
names = pd.Series(['Arun', 'Kirthika', 'Banu', 'Kumar', 'Vasanth', 'Venba', 'Chandru'], name='Names')
ages = pd.Series([40,24,27,32,19,36,20])
genders = pd.Series(['M','F','F','M','M','F','M'])
df = pd.DataFrame({'Name': names, 'Age': ages})
df['Gender'] = genders
df

       Name  Age Gender
0      Arun   40      M
1  Kirthika   24      F
2      Banu   27      F
3     Kumar   32      M
4   Vasanth   19      M
5     Venba   36      F
6   Chandru   20      M

In [14]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})
df = df1.merge(df2)
df

  id  age           job
0  C   25        Doctor
1  D   22  Statistician